<?php 

/**
 * About us view script
 * 
 * @package    Application
 */

$this->headTitle('Impressum');
$this->pageTitle('Impressum und rechtliche Hinweise');
?>
<p>Diese Website wird vom "Verein zur Förderung von Lastenrädern"</p>

<p>
<strong>Anschrift:</strong><br>
Verein zur Förderung von Lastenrädern<br>
c/o Andreas Zobl<br>
Petersgasse 35<br>
8010 Graz<br>
E-mail: <a href="mailto:team@das-lastenrad.at">team@das-lastenrad.at</a><br>
<a href="http://www.das-lastenrad.at">www.das-lastenrad.at</a><br>
<p>ZVR-Zahl: 576525291<br>
Zuständigkeit: Steiermark Landespolizeidirektion LPD</p>

<h3>Nutzungsbedingungen</h3>
<p><a href='/downloads/nutzungsbedingungen_freies_lastenrad.pdf' title='Nutzungsbedingungen' target='blank'><span class="glyphicon glyphicon-download"></span> Nutzungsbedingungen zum Download</a><br>
</p>

<h3>Kooperationspartner</h3>
<p><a href='http://www.diagonale.at' title='Diagonale - Festival des österreichischen Films' target='blank'><img src="/img/logo_diagonale_200.png" alt=""> 
<br>Diagonale - Festival des österreichischen Films</a></p>

<h3>Design</h3>
<p>Flyer und Logo wurden von Katia Tsikrikonaki designt.<br>
<a href='http://www.behance.net/katiatink' title='Grafikdesign von Katia Tsikrikonaki' target='blank'>Portfolio von Katia Tsikrikonaki</a>
</p>

<h3>Fotos</h3>
<p>Für die Fotos bedanken wir uns bei Stephan Pelizzari<br>
<a href='http://www.irgendwasmiteye.com' title='Fotos von Stephan Pelizzari' target='blank'>Mehr Fotos von Stephan Pelizzari</a>
</p>

<h3>Credits</h3>

<p>Für die Unterstützung bedanken wir uns bei den netten Leuten vom Projekt Kasimir<br>
<a href='http://www.kasimir-lastenrad.de/' title='Kasimir - Dein Lastenrad' target='blank'>Kasimir - Dein Lastenrad in Köln</a>
</p>

<p>Den MitarbeiterInnen vom Umweltamt Graz<br>
<a href='http://www.graz.at/umweltamt' title='Umwelt target='blank'>Umweltamt Graz</a>
</p>

<p>Last but not least danken wir unseren NutzerInnen, die das Rad immer nett behandelt und pünktlich zurückgebracht haben.</p>



