<?php 

/**
 * About us view script
 * 
 * @package    Application
 */

$this->headTitle('Über das Lastenrad');
$this->pageTitle('Über das Lastenrad');
?>



<h3>Über das Lastenrad</h3>

<p>Das Lastenrad, das du kostenlos ausleihen kannst, hilft dir, Lasten zu transportieren, die du zu Fuß oder mit einem normalen Fahrrad nicht transportieren kannst, für die du aber kein Auto benötigst. – Also für die allermeisten täglichen und auch nicht alltäglichen Besorgungen und Transporte. Durch den Elektro-Hilfsantrieb kannst du auch mit schweren Lasten steile Straßen hochfahren.
Was kann ich mit einem Lastenrad alles machen oder transportieren?</p>

<ul>
  <li>Die Box ist innen 60 cm breit und 80 cm lang. (Fläche von vier Standard-Getränkekisten.)</li>
  <li>Du kannst zB eine Waschmaschine oder einen Fernseher transportieren.</li>
  <li>Du kannst große Pflanzen für deine Wohnung besorgen.</li>
  <li>Du kannst Sachen vom Baumarkt für Renovierungen herbeischaffen.</li>
  <li>Du kannst spielend leicht für die ganze Familie oder deinen Freundeskreis den Transport zum Grillplatz eurer Wahl übernehmen.</li>
  <li>Du kannst im großen Stil Getränke für deine Party besorgen.</li>
  <li>Du kannst Müll zum Sturzplatz bringen.</li>
  <li>Du kannst Sport-Equipment wie zB Bälle, Luftmatratzen, Schlauchboote usw. transportieren.</li>
  <li>Du kannst es einfach mal ausprobieren und ohne Last lässig durch die Stadt cruisen.</li>
</ul>

<h3>Worauf muss ich achten?</h3>
<ul>
  <li>Bitte beachte, dass du das Lastenrad nicht mehr als zwei Tage  hintereinander und nicht mehr als vier Tage pro Monat ausleihen kannst,  damit es auch andere nutzen können.</li>
  <li>Bitte bring einen Ausweis mit, damit dich die Verleihstation identifizieren kann.</li>
  <li>Fahre bei deinem ersten Mal auf einer wenig befahrenen Straße oder einem Parkplatz und noch ohne Last.</li>
  <li>Achte darauf, dass deine Sachen nicht verrutschen oder aus der Transportbox fallen können.</li>
  <li>Fahre immer vorsichtig und nicht zu schnell.</li>
  <li>Achte besonders auf die anderen Verkehrsteilnehmer und Fußgänger.</li>
  <li>Fahr über keine Kanten wie zB Gehsteige.</li>
  <li>Vermeide Straßen mit Straßenbahnschienen bzw. achte darauf, dass du nicht in Schienen hineinfährst.</li>
  <li>Stelle das Lastenrad immer so ab, dass es niemanden behindert.</li>
  <li>Kette das Lastenrad mit dem Schloss an einen festen Gegenstand an, damit es nicht gestohlen werden kann.</li>
  <li>Wir hoffen es zwar nicht, aber falls du in einen Unfall verwickelt sein solltest, melde uns das bitte umgehend. Wir haben nämlich eine Haftpflichtversicherung abgeschlossen.</li>
</ul>


<h3>Was sind die Vorteile?</h3>
<ul>
  <li>Das Lastenrad kostet dich nichts. (Wir freuen uns aber über eine Spende, die in die Wartung des Lastenrades fließt.)</li>
  <li>Du musst keinen Parkplatz suchen und bezahlen.</li>
  <li>Du bist oft schneller als mit dem Auto, weil du auch Radwege benutzen kannst und nicht im Stau stehst.</li>
  <li>Das Lastenrad ist sehr wendig, aber doch stabil und einfach zu fahren.</li>
  <li>Du tust was gegen den Feinstaub und für die Umwelt.</li>
  <li>Du tust was für deine Fitness.</li>
  <li>Du fällst mit dem Lastenrad positiv auf.</li>
</ul>

