<?php 
/**
 * ZF2 Buch Kapitel 18
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * User-Admin update view script
 * 
 * @package    User
 */

$this->headTitle('Benutzer ändern');
$this->pageTitle('Den ausgewählten Benutzer ändern');

$actionUrl = $this->url('user-admin/action', array(), array(), true);

echo $this->showForm($this->form, $actionUrl, 'form-horizontal');
