<?php 
/**
 * ZF2 Buch Kapitel 19
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Blog
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * namespace definition and usage
 */
use Blog\Entity\BlogEntity;

/**
 * Blog-Admin index view script
 *
 * @package    Blog
 */

$this->headTitle('Blogbeiträge verwalten');
$this->pageTitle('Blogbeiträge verwalten');
?>
<p class="pull-center">
<?php $url = $this->url('blog-admin/action', array('action' => 'create')); ?>
<a href="<?php echo $url; ?>" class="btn">Blogbeitrag anlegen</a>
</p>
<table class="table table-striped table-bordered table-hover table-condensed">
<thead>
<tr>
<th>Überschrift</th>
<th>Datum</th>
<th>Anreißer</th>
<th width="170">Optionen</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->blogList as $blog) : /* @var $blog BlogEntity */ ?>
<?php
$urlEdit = $this->url(
    'blog-admin/action', array('action' => 'update', 'id' => $blog->getId())
);
$urlDelete = $this->url(
    'blog-admin/action', array('action' => 'delete', 'id' => $blog->getId())
);
?>
<tr>
<td><?php echo $blog->getTitle(); ?></td>
<td><?php echo $this->date($blog->getCdate()); ?></td>
<td><?php echo $blog->getTeaser(); ?></td>
<td>
<a href="<?php echo $urlEdit; ?>" class="btn">Ändern</a>
<a href="<?php echo $urlDelete; ?>" class="btn">Löschen</a>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php
echo $this->paginationControl(
    $this->blogList, 'Sliding', 'pagination/sliding', 
    array('route' => 'blog-admin/page')
);
?>
