<?php 
/**
 * ZF2 Buch Kapitel 19
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Blog
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Blog-Admin update view script
 * 
 * @package    Blog
 */

$this->headTitle('Blogbeitrag bearbeiten');
$this->pageTitle('Einen bestehenden Blogbeitrag bearbeiten');

$this->headScript()->appendFile(
    $this->basePath() . '/js/ckeditor/ckeditor.js', 'text/javascript'
);

$actionUrl = $this->url('blog-admin/action', array(), array(), true);

echo $this->showForm($this->form, $actionUrl, 'form-horizontal');
