<?php
/**
 * Footer view script
 * 
 * @package    Application
 */
?>
<footer>
<div class="container">
<div class="row">

<div class="col-lg-6">
  <h3>Ein Projekt vom Verein zur Förderung von Lastenrädern</h3>
  <a href='https://www.facebook.com/dasLastenrad' target='_blank' title="Facebook Fanseite"><img src="/img/facebook_logo_50px.png" alt="Facebook Fanseite"></a>
  <a href='https://twitter.com/dasLastenrad' target='_blank' title="Twitter"><img src="/img/twitter_logo_50px.png" alt="Twitter"></a>
</div>



<div class="col-lg-6 text-right">
  <p>Mit freundlicher Unterstützung von<br><a href="http://www.umwelt.graz.at/" title="Stadt Graz - Umweltamt"><img src="/img/logo_umwelt_stadt_graz_250px.png" alt="Stadt Graz - Umweltamt"></a></p>  
</div>

</div>
</div>
</footer>
