<?php 
/**
 * ZF2 Buch Kapitel 18
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Pizza
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * namespace definition and usage
 */
use Pizza\Entity\PizzaEntity;

/**
 * Pizza-Admin index view script
 *
 * @package    Pizza
 */

$this->headTitle('Pizzen verwalten');
$this->pageTitle('Pizzen verwalten');

?>
<p class="pull-center">
<?php $url = $this->url('pizza-admin/action', array('action' => 'create')); ?>
<a href="<?php echo $url; ?>" class="btn">Pizza anlegen</a>
</p>
<table class="table table-striped table-bordered table-hover table-condensed">
<thead>
<tr>
<th>Name</th>
<th>Preis</th>
<th>Status</th>
<th width="170">Optionen</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->pizzaList as $pizza) : /* @var $pizza PizzaEntity */ ?>
<?php
$urlEdit = $this->url(
    'pizza-admin/action', array('action' => 'update', 'id' => $pizza->getId())
);
$urlDelete = $this->url(
    'pizza-admin/action', array('action' => 'delete', 'id' => $pizza->getId())
);
?>
<tr>
<td><?php echo $pizza->getName(); ?></td>
<td><?php echo $this->currencyFormat($pizza->getPrice()); ?></td>
<td><?php echo $pizza->getStatusName(); ?></td>
<td>
<a href="<?php echo $urlEdit; ?>" class="btn">Ändern</a>
<a href="<?php echo $urlDelete; ?>" class="btn">Löschen</a>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php
echo $this->paginationControl(
    $this->pizzaList, 'Sliding', 'pagination/sliding', 
    array('route' => 'pizza-admin/page')
);
?>
